### ISSUE TITLE
add toggleable option to activate truely view-once-and-destroy mode

### ISSUE THREAD

**Issue by whysthatso** [koderhut/safenotes#42]
**Is your feature request related to a problem? Please describe.**
when reloading the same tab, the information is still present, related to the payload value in the sessionstorage. i understand this is a safety measurement as discussed in #40 

**Describe the solution you'd like**
i'd like to have a configurable 'fragile' option which activates message destruction upon viewing, without any safety net. default can be 'off', but then a notification should show that the message is deleted remotely but will only be deleted  locally once the browser is closed / the browser session is ended (should be very easily understandable by an end user)

**Additional context**
See discussion #40

**Comment by rendler-denis** [comment]
hi, @whysthatso 

I finally managed to get around to adding this. :) 
I've added a cache: true or false option under the static-site > envjs config. By default it is true, but if you want to disable it just put false in your config.

Let me know if there are any bugs.
